### ISSUE TITLE
v1.13.3 config error

### ISSUE THREAD

**Issue by Road-block** [sfmict/CursorMod#2]
[templates.xml#L70](https://github.com/sfmict/CursorMod/blob/dbde23074dc05bd7889c2c26871155509f665e90/templates.xml#L70)

`WHITE_FONT_COLOR` ➡️ `HIGHLIGHT_FONT_COLOR` (WHITE_FONT_COLOR is not a valid global from Constants.lua)

Also see #1

**Comment by sfmict** [comment]
Thx you, fixed.
