### ISSUE TITLE
Cursor Mod Configuration; Scale/opacity and clicking various cursor recolors don't work unfortuately after applying okay.

### ISSUE THREAD

**Issue by destinyher** [sfmict/CursorMod#4]
_
#### Environment
* Addon version: 
* WoW version:

**Comment by sfmict** [comment]
Addon description: Makes mouse pointer remain on screen while mouselook/steering.
The mouse pointer itself, one might say, cannot be changed by addons.

**Comment by destinyher** [comment]
Understood. Thanks for the information.
Sorry about confusion.
