### ISSUE TITLE
Colorchange don't work

### ISSUE THREAD

**Issue by Excalica** [sfmict/CursorMod#5]
Environment
* Addon version: 10.0.1
* WoW version: 10.0.2

How can we reproduce it.  Please be specific
Change settings, colorchange won't appear

What was expected to happen?
Colored cursor

What happened instead?!
nothing

**Comment by sfmict** [comment]
I was unable to reproduce your error. If you meant the cursor itself and not the texture that is displayed when it is hidden, then the addon can't control the cursor itself.
