### ISSUE TITLE
Does not change my cursor

### ISSUE THREAD

**Issue by Filipg88** [sfmict/CursorMod#6]
Addon does not seem to work correctly right now

**Comment by sfmict** [comment]
What the addon version, what wow version, what error? Your message doesn't explain anything.

**Comment by Filipg88** [comment]
Sorry. Its WoW classic. it does not change the cursor or the color.

**Comment by sfmict** [comment]
Makes mouse pointer remain on screen while mouselook/steering.
No more. If this option doesn't work, then the wrong version of the addon is installed.
